# config/services.yaml
parameters:
    consumption_upload_dir: '%kernel.project_dir%/public/uploads/consumption'
    recipes_upload_dir: '%kernel.project_dir%/public/uploads/recipes'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LoginSuccessEvent', method: 'onLoginSuccess' }

    App\Service\OpenAiService:
        arguments:
            $apiKey: '%env(API_KEY)%'
