# config/services.yaml
parameters:
    consumption_upload_dir: '%kernel.project_dir%/public/uploads/consumption'
    recipes_upload_dir: '%kernel.project_dir%/public/uploads/recipes'
    profile_photo_upload_dir: '%kernel.project_dir%/public/uploads/profiles'
    gemini_api_key: '%env(default::GEMINI_API_KEY)%'
    ipinfo_token: '%env(default::IPINFO_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LoginSuccessEvent', method: 'onLoginSuccess' }

    App\Service\IPInfoService:
        arguments:
            $apiToken: '%ipinfo_token%'

    App\EventListener\LoginSecurityListener:
        tags:
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LoginSuccessEvent', method: 'onLoginSuccess' }
            - { name: 'kernel.event_listener', event: 'Symfony\Component\Security\Http\Event\LoginFailureEvent', method: 'onLoginFailure' }

    App\Service\OpenAiService:
        arguments:
            $apiKey: '%env(default::API_KEY)%'
